<?php
$segment = service('uri');
if ($segment->getSegment(2) == 'stageList') {
 
	$AdminDashboard_model = new \App\Models\adminDashboard\AdminDashboard_model();	
   
    $count_efiling_data = $AdminDashboard_model->get_efilied_nums_stage_wise_count();
	
    ?>


    <li><a style="background-color: #737373 !important;"><i class="fa fa-file-o "></i><strong style="color:#fff;">e-Filed Stages</strong></a></li>

    <div class="show_sm_div visible-xs visible-sm" style="margin-top: 6px;"> 
        <div class="side-menu_new">
            <li class="health "><a href="<?php echo ($count_efiling_data->total_new_efiling == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(New_Filing_Stage, ENT_QUOTES))); ?>" class="btn-link">New Filing (<?php echo htmlentities($count_efiling_data->total_new_efiling, ENT_QUOTES); ?>)</a></li>
            <li class="health "><a href="<?php echo ($count_efiling_data->total_not_accepted == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(Initial_Defected_Stage, ENT_QUOTES))); ?>" class="btn-link">For Compliance (<?php echo htmlentities($count_efiling_data->total_not_accepted, ENT_QUOTES); ?>)</a></li>
            <li class="health "><a href="<?php echo ($count_efiling_data->deficit_crt_fee == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(DEFICIT_COURT_FEE, ENT_QUOTES))); ?>" class="btn-link">Pay Deficit Fee (<?php echo htmlentities($count_efiling_data->deficit_crt_fee, ENT_QUOTES); ?>)</a></li>
            <li class="health "><a href="<?php echo ($count_efiling_data->total_refiled_cases == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(Initial_Defects_Cured_Stage, ENT_QUOTES))); ?>" class="btn-link">Complied Objections (<?php echo htmlentities($count_efiling_data->total_refiled_cases, ENT_QUOTES); ?>)</a></li>
            <li class="health "><a href="<?php echo ($count_efiling_data->total_transfer_to_efiling_sec == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(Transfer_to_IB_Stage, ENT_QUOTES))); ?>" class="btn-link">Transfer to ICMIS (<?php echo htmlentities($count_efiling_data->total_transfer_to_efiling_sec, ENT_QUOTES); ?>)</a></li>
            <li class="health "><a href="<?php echo ($count_efiling_data->total_available_for_cis == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(Transfer_to_CIS_Stage, ENT_QUOTES))); ?>" class="btn-link">Get ICMIS Status (<?php echo htmlentities($count_efiling_data->total_available_for_cis, ENT_QUOTES); ?>)</a></li>
            <li class="health "><a href="<?php echo ($count_efiling_data->total_pending_scrutiny == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(I_B_Approval_Pending_Admin_Stage, ENT_QUOTES))); ?>" class="btn-link">Pending Scrutiny (<?php echo htmlentities($count_efiling_data->total_pending_scrutiny, ENT_QUOTES); ?>)</a></li>
            <li class="health "><a href="<?php echo ($count_efiling_data->total_waiting_defect_cured == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(I_B_Defected_Stage, ENT_QUOTES))); ?>" class="btn-link">Defective (<?php echo htmlentities($count_efiling_data->total_waiting_defect_cured, ENT_QUOTES); ?>)</a></li>
            <li class="health "><a href="<?php echo ($count_efiling_data->total_defect_cured == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(I_B_Defects_Cured_Stage, ENT_QUOTES))); ?>" class="btn-link">Defects Cured (<?php echo htmlentities($count_efiling_data->total_defect_cured, ENT_QUOTES); ?>)</a></li>
            <li class="health "><a href="<?php echo ($count_efiling_data->total_efiled_cases == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(E_Filed_Stage, ENT_QUOTES))); ?>" class="btn-link">Cases (<?php echo htmlentities($count_efiling_data->total_efiled_cases, ENT_QUOTES); ?>)</a></li>
            <li class="health "><a href="<?php echo ($count_efiling_data->total_efiled_docs == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(Document_E_Filed, ENT_QUOTES))); ?>" class="btn-link">Documents (<?php echo htmlentities($count_efiling_data->total_efiled_docs, ENT_QUOTES); ?>)</a></li>
            <li class="health "><a href="<?php echo ($count_efiling_data->total_efiled_deficit == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(DEFICIT_COURT_FEE_E_FILED, ENT_QUOTES))); ?>" class="btn-link">Paid Deficit Fee (<?php echo htmlentities($count_efiling_data->total_efiled_deficit, ENT_QUOTES); ?>)</a></li>
            <?php if (ENABLE_E_FILE_IA_FOR_HC || ENABLE_E_FILE_IA_FOR_ESTAB) { ?>
                <li class="health "><a href="<?php echo ($count_efiling_data->total_efiled_ia == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(IA_E_Filed, ENT_QUOTES))); ?>" class="btn-link">IA (<?php echo htmlentities($count_efiling_data->total_efiled_ia, ENT_QUOTES); ?>)</a></li>
            <?php } ?>
            <li class="health "><a href="<?php echo ($count_efiling_data->total_rejected == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(I_B_Rejected_Stage, ENT_QUOTES))); ?>" class="btn-link">Rejected (<?php echo htmlentities($count_efiling_data->total_rejected, ENT_QUOTES); ?>)</a></li>
            <li class="health "><a href="<?php echo ($count_efiling_data->total_lodged_cases == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(LODGING_STAGE, ENT_QUOTES))); ?>" class="btn-link">Idle/Unprocess e-Filed No. (<?php echo htmlentities($count_efiling_data->total_lodged_cases, ENT_QUOTES); ?>)</a></li>
        </div> 
    </div>
    <div class="show_md_div visible-lg visible-md" style="display: none;">
        <ul class="nav side-menu">        
            <li class="highlight"><a href="<?php echo ($count_efiling_data->total_new_efiling == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(New_Filing_Stage, ENT_QUOTES))); ?>"><span class="text_color">New Filing <i class="number_css badge"> <?php echo htmlentities($count_efiling_data->total_new_efiling, ENT_QUOTES); ?></i></span></a></li><div class="clearfix"></div>
            <li class="highlight"><a href="<?php echo ($count_efiling_data->total_not_accepted == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(Initial_Defected_Stage, ENT_QUOTES))); ?>"><span class="text_color">For Compliance<i class="number_css badge"><?php echo htmlentities($count_efiling_data->total_not_accepted, ENT_QUOTES); ?></i></span></a>  </li><div class="clearfix"></div>
            <li class="highlight"><a href="<?php echo ($count_efiling_data->deficit_crt_fee == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(DEFICIT_COURT_FEE, ENT_QUOTES))); ?>"><span class="text_color">Pay Deficit Fee<i class="number_css badge"><?php echo htmlentities($count_efiling_data->deficit_crt_fee, ENT_QUOTES); ?></i></span></a></li><div class="clearfix"></div>
            <li class="highlight"><a href="<?php echo ($count_efiling_data->total_refiled_cases == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(Initial_Defects_Cured_Stage, ENT_QUOTES))); ?>"><span class="text_color">Complied Objections <i class="number_css badge"><?php echo htmlentities($count_efiling_data->total_refiled_cases, ENT_QUOTES); ?></i></span></a></li><div class="clearfix"></div>
            <li class="highlight"><a href="<?php echo ($count_efiling_data->total_transfer_to_efiling_sec == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(Transfer_to_IB_Stage, ENT_QUOTES))); ?>"><span class="text_color">Transfer to ICMIS<i class="number_css badge"><?php echo htmlentities($count_efiling_data->total_transfer_to_efiling_sec, ENT_QUOTES); ?></i></span></a></li><div class="clearfix"></div>
            <li class="highlight"><a href="<?php echo ($count_efiling_data->total_available_for_cis == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(Transfer_to_CIS_Stage, ENT_QUOTES))); ?>"><span class="text_color" >Get ICMIS Status<i class="number_css badge"><?php echo htmlentities($count_efiling_data->total_available_for_cis, ENT_QUOTES); ?></i></span></a></li><div class="clearfix"></div>
            <li class="highlight"><a href="<?php echo ($count_efiling_data->total_pending_scrutiny == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(I_B_Approval_Pending_Admin_Stage, ENT_QUOTES))); ?>"><span class="text_color">Pending Scrutiny<i class="number_css badge"><?php echo htmlentities($count_efiling_data->total_pending_scrutiny, ENT_QUOTES); ?></i></span></a></li><div class="clearfix"></div>
            <li class="highlight"><a href="<?php echo ($count_efiling_data->total_waiting_defect_cured == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(I_B_Defected_Stage, ENT_QUOTES))); ?>"><span class="text_color" >Defective<i class="number_css badge"><?php echo htmlentities($count_efiling_data->total_waiting_defect_cured, ENT_QUOTES); ?></i></span></a></li><div class="clearfix"></div>
            <li class="highlight"><a href="<?php echo ($count_efiling_data->total_defect_cured == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(I_B_Defects_Cured_Stage, ENT_QUOTES))); ?>"><span class="text_color" >Defects Cured<i class="number_css badge"><?php echo htmlentities($count_efiling_data->total_defect_cured, ENT_QUOTES); ?></i></span></a></li><div class="clearfix"></div>
            <li class="highlight"><a href="<?php echo ($count_efiling_data->total_efiled_cases == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(E_Filed_Stage, ENT_QUOTES))); ?>" ><span class="text_color" >Cases<i class="number_css badge"><?php echo htmlentities($count_efiling_data->total_efiled_cases, ENT_QUOTES); ?></i></span></a></li><div class="clearfix"></div>
            <li class="highlight"><a href="<?php echo ($count_efiling_data->total_efiled_docs == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(Document_E_Filed, ENT_QUOTES))) ?>"><span class="text_color" >Documents<i class="number_css badge"><?php echo htmlentities($count_efiling_data->total_efiled_docs, ENT_QUOTES); ?></i></span></a></li><div class="clearfix"></div>
            <li class="highlight"><a href="<?php echo ($count_efiling_data->total_efiled_deficit == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(DEFICIT_COURT_FEE_E_FILED, ENT_QUOTES))); ?>"><span class="text_color" >Paid Deficit Fee<i class="number_css badge"><?php echo htmlentities($count_efiling_data->total_efiled_deficit, ENT_QUOTES); ?></i></span></a></li><div class="clearfix"></div>
            <!--<li class="highlight"><a href="<?php /*echo ($count_efiling_data->total_efiled_deficit == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(DEFICIT_COURT_FEE_PAID, ENT_QUOTES))); */?>"><span class="text_color" >Paid Deficit Fee<i class="number_css badge"><?php /*echo htmlentities($count_efiling_data->total_efiled_deficit, ENT_QUOTES); */?></i></span></a></li><div class="clearfix"></div>-->
            <li class="highlight"><a href="<?php echo ($count_efiling_data->total_efiled_ia == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(IA_E_Filed, ENT_QUOTES))); ?>"><span class="text_color" >IA<i class="number_css badge"><?php echo htmlentities($count_efiling_data->total_efiled_ia, ENT_QUOTES); ?></i></span></a></li>  <div class="clearfix"></div>
            <li class="highlight"><a href="<?php echo ($count_efiling_data->total_rejected == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(I_B_Rejected_Stage, ENT_QUOTES))) ?>"><span class="text_color" >Rejected<i class="number_css badge"><?php echo htmlentities($count_efiling_data->total_rejected, ENT_QUOTES); ?></i></span></a></li>  <div class="clearfix"></div>
            <li class="highlight"><a href="<?php echo ($count_efiling_data->total_lodged_cases == '0' ) ? 'javascript:void(0)' : base_url("adminDashboard/stageList/" . htmlentities(url_encryption(I_B_Defected_Stage, ENT_QUOTES))) ?>"><span class="text_color" >Idle/Unprocessed e-Filed No.'s<i class="number_css badge"><?php echo htmlentities($count_efiling_data->total_lodged_cases, ENT_QUOTES); ?></i></span></a></li><div class="clearfix"></div>
        </ul>
    </div>
    <?php
    // Ends User Dashboard Stages list
}?>