
<div class="modal fade" id="eSignDeclaration_model" role="dialog">
    <div class="modal-dialog" style="width: 850px">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" style="text-align: center">
                    Aadhaar-Holder Consent Format<br>
                    <i>National Informatics Centre</i>
                </h4>
            </div>

            <div class="modal-body">
                <p> I hereby state that I have no objection in authenticating myself with Aadhaar based authentication sytem and consent to providing 
                    my Aadhaar number,Biometric and/or One Time Pin (OTP) data for Aadhaar based authentication from UIDAI, for the purpose of availing of 
                    eSign Service from eSign Provider (C-DAC) <b>through nic-eSign Getway service and consumed in eFiling Software  from eCommittee, Supreme Court of India </b>
                    as Application Service Provider. I understand that the Biometrics and/or OTP I provide for authentication shall be used only for authenticating
                    my identity through the Aadhaar Authentication system, for obtaining my e-KYC through Aadhaar e-KYC
                    service and for the issuance of Digital Signature Certificate (DSC) for this specific transaction and for no other purpose. For the creation of DSC, I understand that the option that I have chosen are the ones that shall be populated in the DSC generated by the CA (C-DAC)
                    and I provide my consent for the same.

                </p>
                <p> I also understand that the following fields in the DSC generated by the CA (C-DAC) are mandatory and I give my consent for using the Aadhaar provided e-KYC information to populate the corresponding fields in the DSC. </p>
                <ul>
                    <li> Common Name (name as obtained from e-KYC)</li>
                    <li> Unique Identifier (hash of Aadhaar number) </li>
                    <li> Pseudonym (unique code send by UIDAI in e-KYC response) </li>
                    <li> State or Province (State as obtained from e-KYC) </li>
                    <li> Postal Code (postal code as obtained from e-KYC) </li>
                    <li> Telephone Number (hash of phone as obtained from e-KYC) </li>
                </ul>
                <p>I understand that <b> eCommittee, Supreme Court of India </b>shall ensure security and confidentiality of my purpose identity data provided for the purpose of Aadhaar based authentication.</p>

            </div>

            <div class="modal-footer">

            </div>

        </div>
    </div>
</div>


<div class="panel panel-default">
    <table class="table table-striped">
        <?php if($certificate_lock_status){ ?>
        <thead>
        <tr>
            <th>Party</th>
            <th>Email</th>
            <th>Request sent on</th>
            <th>Signed on</th>
            <th>Signed?</th>
            <th>Sign URL</th>
        </tr>
        </thead>
        <?php } ?>
        <tbody>
        <?php
        $pending_sign_flags=0;
        $pending_signer='';
        //var_dump($certificate_lock_status);
        foreach($certificate_lock_status as $signer){
            if($signer['is_certificate_signed']!='t'){
                $pending_sign_flags++;
                if(!empty($signer['request_sent_on']))
                    $pending_signer=$signer['email'];
            }
            
        ?>
        <tr>
            <td><?=$signer['party_name'].' ('.$signer['p_r_type'].')'?></td>
            <td><?=$signer['email']?></td>
            <td><?=$x=(!empty($signer['request_sent_on']))?date('d-m-Y H:i:s', strtotime($signer['request_sent_on'])):''?></td>
            <td><?=$x=(!empty($signer['signed_on']))?date('d-m-Y H:i:s', strtotime($signer['signed_on'])):''?></td>
            <td><?=($signer['is_certificate_signed']=='t')?'<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="green" class="bi bi-check-square-fill" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm10.03 4.97a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
</svg>':(!empty($signer['request_sent_on'])?'<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="red" class="bi bi-x-circle-fill" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM5.354 4.646a.5.5 0 1 0-.708.708L7.293 8l-2.647 2.646a.5.5 0 0 0 .708.708L8 8.707l2.646 2.647a.5.5 0 0 0 .708-.708L8.707 8l2.647-2.646a.5.5 0 0 0-.708-.708L8 7.293 5.354 4.646z"/>
</svg>':'<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="olive" class="bi bi-pause-fill" viewBox="0 0 16 16">
  <path d="M5.5 3.5A1.5 1.5 0 0 1 7 5v6a1.5 1.5 0 0 1-3 0V5a1.5 1.5 0 0 1 1.5-1.5zm5 0A1.5 1.5 0 0 1 12 5v6a1.5 1.5 0 0 1-3 0V5a1.5 1.5 0 0 1 1.5-1.5z"/>
</svg>')?></td>
            <td><span onclick="copyUrl('<?=$signer['sign_url']?>')" style="cursor:pointer" id="myUrl" class = "label label-default"><?=(empty($signer['signed_on']) && $signer['sign_url'])?'Click to copy':''?></span></td>
        </tr>
        <?php } ?>
        </tbody>
    </table>
    
    
    <?php
    if($pending_sign_flags>0){
        ?>
        <div class="alert alert-info" role="alert">
            <h4 class="alert-heading">Request pending </h4>
            A request for signing the document has already been sent to <b><?=$pending_signer?></b>.
            The page will be available as soon as the document is signed.
        </div>

    <?php }
    else if ($esigned_docs_details[0]->is_data_valid != 't') { ?>
        <h4 style="text-align: center">Advocate Certificate</h4><br>
        <div class="clearfix"></div>
        <div class="col-lg-12 ccol-md-12 col-xs-12 text-center">
            <div class="form-group">
                <span>Sign Method :</span>
                <label class="radio-inline"><input type="radio" name="doc_sign" id="doc_sign1" value="1" onclick="sign_doc_view('1')" checked="checked" >Digital Sign Using Token</label>
                <label class="radio-inline"><input type="radio" name="doc_sign" id="doc_sign2" value="2" onclick="sign_doc_view('2')" >eSign Using Aadhaar</label>
    <!--                <label class="radio-inline"><input type="radio" name="doc_sign" id="doc_sign3" value="3" onclick="sign_doc_view('3')" <?php if ($esigned_docs_details[0]->signed_type == 3 || !empty($_SESSION['eVerified_mobile_otp']['LITIGENT_MOB_OTP_VERIFY'])) { ?>checked="" <?php } ?>>Mobile OTP</label>-->

            </div>
        </div>
    
    <div class="clearfix"></div>
    <br><br>
    <div class="clearfix"></div>    
    <div id="aadhar" style="display: none">
        <?php include('case_aadhaar_esign_view.php'); ?>
    </div>
    <div id="digital_sign" style="display:block">
        <?php include('case_digitally_signed_view.php'); ?>
    </div>
    <div id="mobile_otp" style="display: none">
        <?php include('case_mobile_otp_everified_view.php'); ?>
    </div>
<?php }else {
    
    $this->load->view('affirmation/submitted_certificate_view');
    
    } ?>
    <div class="row">
        <div class="text-center">
            <?php
            if ($_SESSION['efiling_details']['ref_m_efiled_type_id'] == E_FILING_TYPE_NEW_CASE) {
                $prev_url = base_url('newcase/courtFee');
                $next_url = base_url('newcase/view');
            } elseif ($_SESSION['efiling_details']['ref_m_efiled_type_id'] == E_FILING_TYPE_MISC_DOCS) {
                $prev_url = base_url('miscellaneous_docs/courtFee');
                $next_url = base_url('miscellaneous_docs/view');
            } elseif ($_SESSION['efiling_details']['ref_m_efiled_type_id'] == E_FILING_TYPE_IA) {
                $prev_url = base_url('IA/courtFee');
                $next_url = base_url('IA/view');
            } elseif ($_SESSION['efiling_details']['ref_m_efiled_type_id'] == E_FILING_TYPE_MENTIONING) {
                $prev_url = base_url('mentioning/courtFee');
                $next_url = base_url('mentioning/view');
            }elseif ($_SESSION['efiling_details']['ref_m_efiled_type_id'] == E_FILING_TYPE_JAIL_PETITION) {
                $prev_url = base_url('uploadDocuments/upload_document');
                $next_url = base_url('jailPetition/view');
            } else {
                $prev_url = '#';
                $next_url = '#';
            }
            ?>
            <a href="<?= $prev_url ?>" class="btn btn-primary btnPrevious" type="button">Previous</a>
            <?php if(!($pending_sign_flags>0)){?><a href="<?= $next_url ?>" class="btn btn-primary btnNext" type="button">Next</a><?php } ?>

        </div>
    </div>
    <script>
        
        function sign_doc_view(signtype) {

            var CSRF_TOKEN = 'CSRF_TOKEN';
            var CSRF_TOKEN_VALUE = $('[name="CSRF_TOKEN"]').val();
            if (signtype == 1) {

                $("#digital_sign").show();
                $("#aadhar").hide();
                $("#mobile_otp").hide();
            } else if (signtype == 2) {

                $("#aadhar").show();
                $("#digital_sign").hide();
                $("#mobile_otp").hide();
            } else if (signtype == 3) {

                $("#aadhar").hide();
                $("#digital_sign").hide();
                $("#mobile_otp").show();
            } else {

                $("#aadhar").hide();
                $("#digital_sign").show();
                $("#mobile_otp").hide();
            }

        }
    </script>
    <script type="text/javascript">
        function copyUrl(txt) {
            var input_temp = document.createElement("input");
            input_temp.value = txt;
            document.body.appendChild(input_temp);
            input_temp.select();
            document.execCommand("copy");
            document.body.removeChild(input_temp);
        }
        
        function onclick_eSign(element) {

            var adv_name_as_on_aadhar = $('#adv_name_as_on_aadhar').val();

            if (element == 'advocate_id')
            {
                if (adv_name_as_on_aadhar == "")
                {
                    $('#msg').show();
                    $(".form-response").html("<p class='message invalid' id='msgdiv'>&nbsp;&nbsp;&nbsp; " + 'Enter Advocate Name as on Aadhaar' + "  <span class='close' onclick=hideMessageDiv()>X</span></p>");
                    return false;
                }

            } else
            {
                $('#msg').show();
                $(".form-response").html("<p class='message invalid' id='msgdiv'>&nbsp;&nbsp;&nbsp; " + 'Invalid Input' + "  <span class='close' onclick=hideMessageDiv()>X</span></p>");
                return false;
            }

            $('#eSignDeclaration_model').modal('show');
            $('#eSignDeclaration_model .modal-footer').html('<div style="text-align: center"><button type="button" name="adv_aadhaar_procces" id="adv_aadhaar_procces" onclick="return aadhaarSubmitForm(\'' + element + '\');" class="btn btn-primary">Proceed</button><button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button></div>');

        }
        function aadhaarSubmitForm(element) {

            if (element == 'advocate_id') {

                $('#adv_esign_cert').submit();
            }
        }

        $('.reset_affirmation').click(function () {

            var CSRF_TOKEN = 'CSRF_TOKEN';
            //var CSRF_TOKEN_VALUE = $('[name="CSRF_TOKEN"]').val();
            var CSRF_TOKEN_VALUE ='<?php echo $this->security->get_csrf_hash();?>';
            var docid = $(this).data("docid");
            var type = $(this).attr("id");
            $.ajax({
                type: "POST",
                url: "<?= base_url('affirmation/reset'); ?>",
                data: {CSRF_TOKEN: CSRF_TOKEN_VALUE, docid: docid, type: type},
                success: function (data) {
                    location.reload();


                    $.getJSON("<?php echo base_url('csrftoken'); ?>", function (result) {
                        $('[name="CSRF_TOKEN"]').val(result.CSRF_TOKEN_VALUE);
                    });
                },
                error: function (result) {
                    $.getJSON("<?php echo base_url('csrftoken'); ?>", function (result) {
                        $('[name="CSRF_TOKEN"]').val(result.CSRF_TOKEN_VALUE);
                    });
                }
            });
        });
        function onclick_eVerified() {
            var CSRF_TOKEN = 'CSRF_TOKEN';
            var CSRF_TOKEN_VALUE = $('[name="CSRF_TOKEN"]').val();

            $.ajax({
                type: "POST",
                url: "<?= base_url('new_case/send_mobile_otp_to_everified_doc'); ?>",
                data: {CSRF_TOKEN: CSRF_TOKEN_VALUE},
                success: function (data) {
                    if (data == 'done') {
                        location.reload();
                    } else {
                        $('#msg').show();
                        $(".form-response").html("<p class='message invalid' id='msgdiv'>Fail to send OTP. Please try after some time. <span class='close' onclick=hideMessageDiv()>X</span></p>");

                    }

                    $.getJSON("<?php echo base_url() . 'csrftoken'; ?>", function (result) {
                        $('[name="CSRF_TOKEN"]').val(result.CSRF_TOKEN_VALUE);
                    });
                },
                error: function (result) {
                    $.getJSON("<?php echo base_url() . 'csrftoken'; ?>", function (result) {
                        $('[name="CSRF_TOKEN"]').val(result.CSRF_TOKEN_VALUE);
                    });
                }
            });
        }

    </script>