<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Welcome to CodeIgniter</title>

    <style type="text/css">

        ::selection { background-color: #E13300; color: white; }
        ::-moz-selection { background-color: #E13300; color: white; }

        body {
            background-color: #fff;
            margin: 40px;
            font: 13px/20px normal Helvetica, Arial, sans-serif;
            color: #4F5155;
        }

        a {
            color: #003399;
            background-color: transparent;
            font-weight: normal;
        }

        h1 {
            color: #444;
            text-align: center;
            background-color: transparent;
            border-bottom: 1px solid #D0D0D0;
            font-size: 19px;
            font-weight: normal;
            margin: 0 0 14px 0;
            padding: 14px 15px 10px 15px;
        }

        code {
            font-family: Consolas, Monaco, Courier New, Courier, monospace;
            font-size: 12px;
            background-color: #f9f9f9;
            border: 1px solid #D0D0D0;
            color: #002166;
            display: block;
            margin: 14px 0 14px 0;
            padding: 12px 10px 12px 10px;
        }

        #body {
            margin: 0 15px 0 15px;
        }

        p.footer {
            text-align: right;
            font-size: 11px;
            border-top: 1px solid #D0D0D0;
            line-height: 32px;
            padding: 0 10px 0 10px;
            margin: 20px 0 0 0;
        }

        #container {
            margin: 10px;
            border: 1px solid #D0D0D0;
            box-shadow: 0 0 8px #D0D0D0;
        }
    </style>
</head>
<body>

<div id="container">
    
    <?php
    $file_path = base_url("affirmation/viewUnsignedCertificate/get_certificate/".$signer_list[0]['estab_code']."/".$signer_list[0]['efiling_no']);
    $response_uri = base_url("affirmation/Esign_signature/mail_signed_response/".$signer_list[0]['efiling_no']."/".$signer_list[0]['uuid']);
    ?>
    <h1>Aadhaar-Holder Consent Format<br>
        <i>National Informatics Centre</i></h1>
    <div id="body">
        <p> I hereby state that I have no objection in authenticating myself with Aadhaar based authentication sytem and consent to providing
            my Aadhaar number,Biometric and/or One Time Pin (OTP) data for Aadhaar based authentication from UIDAI, for the purpose of availing of
            eSign Service from eSign Provider (C-DAC) <b>through nic-eSign Getway service and consumed in eFiling Software  from eCommittee, Supreme Court of India </b>
            as Application Service Provider. I understand that the Biometrics and/or OTP I provide for authentication shall be used only for authenticating
            my identity through the Aadhaar Authentication system, for obtaining my e-KYC through Aadhaar e-KYC
            service and for the issuance of Digital Signature Certificate (DSC) for this specific transaction and for no other purpose. For the creation of DSC, I understand that the option that I have chosen are the ones that shall be populated in the DSC generated by the CA (C-DAC)
            and I provide my consent for the same.

        </p>
        <p> I also understand that the following fields in the DSC generated by the CA (C-DAC) are mandatory and I give my consent for using the Aadhaar provided e-KYC information to populate the corresponding fields in the DSC. </p>
        <ul>
            <li> Common Name (name as obtained from e-KYC)</li>
            <li> Unique Identifier (hash of Aadhaar number) </li>
            <li> Pseudonym (unique code send by UIDAI in e-KYC response) </li>
            <li> State or Province (State as obtained from e-KYC) </li>
            <li> Postal Code (postal code as obtained from e-KYC) </li>
            <li> Telephone Number (hash of phone as obtained from e-KYC) </li>
        </ul>
        <p>I understand that <b> eCommittee, Supreme Court of India </b>shall ensure security and confidentiality of my purpose identity data provided for the purpose of Aadhaar based authentication.</p>
        

        <code><a href="<?=$file_path?>" target="_blank">Click to view Certificate</a> </code>
        
        <?php
        $attribute = array('target' => '_top', 'name' => 'test', 'id' => 'test', 'autocomplete' => 'off');
        $p_r_type = ($party_details[0]['p_r_type']=='P')?'Petitioner':(($party_details[0]['p_r_type']=='R')?'Respondent':$party_details[0]['p_r_type']);
        $m_a_type = ($party_details[0]['m_a_type']=='M')?'Main':(($party_details[0]['m_a_type']=='A')?'Additional':$party_details[0]['m_a_type']);
        $type = $p_r_type.((trim($m_a_type)=='')?'':'-').$m_a_type;
        $party_name = empty($party_details[0]['party_name'])?'x':$party_details[0]['party_name'];
        echo form_open(ESIGN_SERVICE_URL, $attribute); //Server
        echo '<input type = "hidden" name = "docId" value = "'.$signer_list[0]['id'].'" />';
        echo '<input type = "hidden" name = "url" value = "'.$file_path.'" />';
        echo '<input type = "hidden" name = "respone_url" value = "'.$response_uri.'" />';
        echo '<input type = "hidden" name = "docType" value = "'.$signer_list[0]['efiling_no'].'" />';
        echo '<input type = "hidden" name = "esignIndex" value = "'.$sign_count[0]['sign_count'].'" />';
        echo '<input type = "hidden" name = "employeeName" value = "Supreme Court" />';
        echo '<input type = "hidden" name = "employeeCode" value = "'.$party_name.'" />';
        echo '<input type = "hidden" name = "employeeDesignation" value = "'.$type.'" />';
        echo '<input type = "submit" />';
        echo form_close();
        ?>
        
        
    </div>

    <p class="footer"></p>
</div>

</body>
</html>